version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/easyparking
      - JWT_SECRET=easyparking_super_secret_jwt_key_2024
      - CHAPA_SECRET_KEY=CHASECK_TEST-kbwJbJRUZhbjYYyqvLrXqBU7R0KAdhAO
      - CHAPA_PUBLIC_KEY=CHAPUBK_TEST-48UTwCCQSTiJmDdcwLDtLCtHycoj7jUo
      - FRONTEND_URL=http://localhost:5000
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
