services:
  - type: web
    name: easy-parking
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CI
        value: "false"
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CHAPA_SECRET_KEY
        sync: false
      - key: CHAPA_PUBLIC_KEY
        sync: false
